name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install libpng
        run: sudo apt-get install -y libpng-dev docbook-utils
      - name: aclocal
        run: aclocal
      - name: autoconf
        run: autoconf
      - name: automake --add-missing
        run: automake --add-missing
      - name: autoreconf
        run: autoreconf
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make install
        run: make install DESTDIR="$PWD/install"
